development:
  cloud_name: 'hupxp3pqa'
  api_key: '449838773631474'
  api_secret: 'FHNa5wYwnJHYJTKwQxqmsRKDARU'
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: 'hupxp3pqa'
  api_key: '449838773631474'
  api_secret: 'FHNa5wYwnJHYJTKwQxqmsRKDARU'
  enhance_image_tag: true
  static_file_support: true